#!/usr/bin/env Rscript
install.packages(c(
        "adabag",
        "caret",
        "DiscriMiner",
        "e1071",
        "datasauRus",
        "forecast",
        "gains",
        "gbm",
        "ggplot2",
        "glmnet",
        "knitr",
        "leaps",
        "mapproj",
        "maps",
        "markdown",
        "Metrics",
        "neuralnet",
        "parsnip",
        "plm",
        "randomForest",
        "rpart.plot",
        "stargazer",
        "tidymodels",
        "tidyverse",
        "tree",
        "xgboost"),
    repo = "https://cloud.r-project.org")

# part of installation of other packages
#       "boot",
#       "MASS",
#       "rpart",
#       "tidyr",
